### ISSUE TITLE
IndexOutOfRange Exception

### ISSUE THREAD

**Issue by MishaTy** [SamboyCoding/AudicaShredder#10]
Hi, there is a null reference exception in the part where it reads the generic methods.

```
Stack trace:
        Reading generic methods...Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LibCpp2IL.Il2CppBinary.GetMethodSpec(Int32 index)
   at LibCpp2IL.Il2CppBinary.GetGenericMethodFromIndex(Int32 genericMethodIndex, Int32 genericMethodPointerIndex, Il2CppConcreteGenericMethod& concreteMethod)
   at LibCpp2IL.Il2CppBinary.Init(UInt64 pCodeRegistration, UInt64 pMetadataRegistration)
   at LibCpp2IL.PE.PE.AutoInit(UInt64 pCodeRegistration, UInt64 pMetadataRegistration)
   at LibCpp2IL.PE.PE.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount)
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion)
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, Int32[] unityVersion)
   at Cpp2IL.Cpp2IlTasks.InitializeLibCpp2Il(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)
```

The game is Among Us. (again)

**Comment by SamboyCoding** [comment]
Should be fixed in 9216228
