### ISSUE TITLE
Weird errors during analysis when running latest error

### ISSUE THREAD

**Issue by MishaTy** [SamboyCoding/AudicaShredder#18]
I get alot of analysis errors when running the latest version
```
[Warn] [Program] Failed to generate synopsis for method System.Void GarbageBehaviour::EPKJEAPPPOJ(), instruction mov byte ptr ds:[129BA1EBh],1 at 0x11386F5C - got exception System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at LibCpp2IL.Metadata.Il2CppMetadata.GetStringLiteralFromIndex(UInt32 index)
   at LibCpp2IL.MetadataUsage.AsLiteral()
   at LibCpp2IL.MetadataUsage.ToString()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at Cpp2IL.Analysis.Actions.ConstantToGlobalAction.ToTextSummary()
   at Cpp2IL.Analysis.Actions.BaseAction.GetSynopsisEntry()
   at Cpp2IL.Analysis.AsmAnalyzer.BuildMethodFunctionality()
```
Game: Among Us

**Comment by SamboyCoding** [comment]
This is expected. Analysis has some not yet implemented features and tweaks needed - it is a very work-in-progress system and everything is constantly moving. Sometimes things will fail.

**Comment by SamboyCoding** [comment]
My apologies, this was actually a bug - I didn't read the stacktrace properly and thought it was another, known, issue.
