### ISSUE TITLE
Fatal Exception initializing LibCpp2IL! (Rec Room)

### ISSUE THREAD

**Issue by TheanMcGarity** [SamboyCoding/AudicaShredder#206]
===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.

[Info] [Program] Running on Win32NT
[Info] [Program] Determined game's unity version to be 2020.3.33
[Info] [Library] Initializing Metadata...
[Info] [Library]        Using actual IL2CPP Metadata version 27.1
[Info] [Library] Initialized Metadata in 1710ms
[Info] [Library] Searching Binary for Required Data...
[Fail] [Program]

Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ```
---> System.Exception: Failed to find pCodegenModules
   at LibCpp2IL.BinarySearcher.FindCodeRegistrationPost2019()
   at LibCpp2IL.Il2CppBinary.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount)
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion)
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, Int32[] unityVersion)
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)
```

Waiting for you to press enter - feel free to copy the error...

**Comment by SamboyCoding** [comment]
This *may* have been addressed by https://github.com/SamboyCoding/Cpp2IL/commit/dc9dcd9bce20c7ba935a38bf092ea4e52b2451a6, could you check and see if it works on the latest github actions build, which you can get from [here](https://nightly.link/SamboyCoding/Cpp2IL/workflows/dotnet-core/new-analysis)

**Comment by Kneesnap** [comment]
I can verify this new build did address the original problem. However, other warnings and exceptions are printed.

![image](https://user-images.githubusercontent.com/6562913/220575105-097cfdaa-bdbb-450a-95e2-08eab383ec1e.png)
![image](https://user-images.githubusercontent.com/6562913/220575258-b2a4b97f-8bdc-4358-8da2-398edd00dc92.png)

**Comment by SamboyCoding** [comment]
Those aren't related, they're basically expected
