### ISSUE TITLE
Fatal Exception initializing LibCpp2IL! (SummonersWarChronicles)

### ISSUE THREAD

**Issue by lonebug11** [SamboyCoding/AudicaShredder#217]
===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.

[Info] [Program] Running on Win32NT
[Info] [Program] Determined game's unity version to be 2020.3.33
[Info] [Library] Initializing Metadata...
[Info] [Library]        Using actual IL2CPP Metadata version 27,1
[Info] [Library] Initialized Metadata in 1714ms
[Info] [Library] Searching Binary for Required Data...
[Fail] [Program]

```
Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.Exception: Failed to find pCodegenModules
   at LibCpp2IL.BinarySearcher.FindCodeRegistrationPost2019()
   at LibCpp2IL.Il2CppBinary.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount)
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion)
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, Int32[] unityVersion)
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)

```
Waiting for you to press enter - feel free to copy the error...

Not sure why this is happening, is there anything I can do to help you fix this error?

**Comment by SamboyCoding** [comment]
Can you try with the latest nightly version, either from github actions or https://nightly.link/SamboyCoding/Cpp2IL/workflows/dotnet-core/new-analysis

**Comment by lonebug11** [comment]
> Can you try with the latest nightly version, either from github actions or https://nightly.link/SamboyCoding/Cpp2IL/workflows/dotnet-core/new-analysis

I saw the earlier issue and tried with the nightly version;
https://nightly.link/SamboyCoding/Cpp2IL/workflows/dotnet-core/new-analysis/Cpp2IL-Windows.zip

But no success

**Comment by SamboyCoding** [comment]
> SummonersWarChronicles

Sorry, I'm just getting around to this issue, and all versions of this game I can find have encrypted metadata files. Even if you can decrypt them, it's likely that they've also made modifications to the binary file layout, which is why this isn't working.
