### ISSUE TITLE
 System.InvalidOperationException: Sequence contains no elements

### ISSUE THREAD

**Issue by Hiro420** [SamboyCoding/AudicaShredder#224]
[Info] [Library] Initializing Metadata...
[Info] [Library]        Using actual IL2CPP Metadata version 24

Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at LibCpp2IL.Metadata.Il2CppMetadata.<>c.<DecipherMetadataUsage>b__33_0(KeyValuePair`2 x) in C:\Users\nikur\Documents\Cpp2IL\LibCpp2IL\Metadata\Il2CppMetadata.cs:line 304
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source)
   at LibCpp2IL.Metadata.Il2CppMetadata.DecipherMetadataUsage() in C:\Users\nikur\Documents\Cpp2IL\LibCpp2IL\Metadata\Il2CppMetadata.cs:line 304
   at LibCpp2IL.Metadata.Il2CppMetadata..ctor(MemoryStream stream) in C:\Users\nikur\Documents\Cpp2IL\LibCpp2IL\Metadata\Il2CppMetadata.cs:line 236
   at LibCpp2IL.Metadata.Il2CppMetadata.ReadFrom(Byte[] bytes, Int32[] unityVer) in C:\Users\nikur\Documents\Cpp2IL\LibCpp2IL\Metadata\Il2CppMetadata.cs:line 114
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion) in C:\Users\nikur\Documents\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 150
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, Int32[] unityVersion) in C:\Users\nikur\Documents\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 248
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in C:\Users\nikur\Documents\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 182
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\nikur\Documents\Cpp2IL\Cpp2IL\Program.cs:line 445
   at Cpp2IL.Program.Main(String[] args) in C:\Users\nikur\Documents\Cpp2IL\Cpp2IL\Program.cs:line 393
   
   
   is there a way to hardcode the metadata registration offests?

**Comment by nitrog0d** [comment]
☠️☠️☠️☠️☠️☠️☠️☠️☠️
