### ISSUE TITLE
Add Support for Unity 2021.3.9f1

### ISSUE THREAD

**Issue by MintzHydra** [SamboyCoding/AudicaShredder#229]
been looking for il2cppinspector that support 2021.3.9f1 but seem the repo is unmaintaned...and no guide how to update it...looking for cpp2il that support 2021.3.9f1 thank you

**Comment by SamboyCoding** [comment]
Cpp2il does support 2021.3.9

**Comment by MintzHydra** [comment]
which version? the latest released or build from sources?

**Comment by MintzHydra** [comment]
it said 
===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.
Version 2022.1.0-pre-release.12

[Info] [Program] Running on Win32NT
[Info] [Plugins] Loading plugins from D:\ModToramPython\Cpp2IL-2022.1.0-pre-release.12-Windows-Netframework472\Plugins...
[Info] [Plugins] Using Plugin: Cpp2IL Built-In
[Fail] [Program] Execution Failed: Could not find a valid unity game at C:\Program

**Comment by SamboyCoding** [comment]
put quotes around the game path

**Comment by MintzHydra** [comment]
now its appear
[Fail] [Program]

Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL! ---> System.Exception: Failed to find pCodegenModules
   at LibCpp2IL.BinarySearcher.FindCodeRegistrationPost2019() in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\BinarySearcher.cs:line 196
   at LibCpp2IL.Il2CppBinary.FindCodeAndMetadataReg(Int32 methodCount, Int32 typeDefinitionsCount) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\Il2CppBinary.cs:line 450
   at LibCpp2IL.LibCpp2IlBinaryRegistry.CreateAndInit(Byte[] buffer, Il2CppMetadata metadata) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlBinaryRegistry.cs:line 68
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, UnityVersion unityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 159
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, UnityVersion unityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 202
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 55
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 67
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 487
   at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 429

Waiting for you to press enter - feel free to copy the error...

**Comment by MintzHydra** [comment]
the other error appeared

**Comment by SamboyCoding** [comment]
Try a release build not a pre-release

**Comment by MintzHydra** [comment]
the release build has error too

[Fail] [Program]

Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL! ---> System.Exception: Failed to find pCodegenModules
   at LibCpp2IL.BinarySearcher.FindCodeRegistrationPost2019() in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/BinarySearcher.cs:line 178
   at LibCpp2IL.Il2CppBinary.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/Il2CppBinary.cs:line 419
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlMain.cs:line 166
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in /home/runner/work/Cpp2IL/Cpp2IL/Cpp2IL.Core/Cpp2IlApi.cs:line 176
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in /home/runner/work/Cpp2IL/Cpp2IL/Cpp2IL.Core/Cpp2IlApi.cs:line 190
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in /home/runner/work/Cpp2IL/Cpp2IL/Cpp2IL/Program.cs:line 387
   at Cpp2IL.Program.Main(String[] args) in /home/runner/work/Cpp2IL/Cpp2IL/Cpp2IL/Program.cs:line 331

Waiting for you to press enter - feel free to copy the error...

**Comment by SamboyCoding** [comment]
That usually implies your game is protected somehow.

**Comment by SamboyCoding** [comment]
I can say for certain that 2021.3.12f1, 2021.3.16f1, and 2021.3.26f1 all work

**Comment by MintzHydra** [comment]
do you have a solution? because il2cpp inspector that usually i used is not supported 2021.3.9f1 yet

**Comment by MintzHydra** [comment]
Or maybe there are other similar applications?

**Comment by MintzHydra** [comment]
![image](https://github.com/SamboyCoding/Cpp2IL/assets/106018741/acd84c40-f13f-4f20-a50a-c8754ed0c4c4)
