### ISSUE TITLE
First time use CPP2IL and getting errors 

### ISSUE THREAD

**Issue by JeanTheFungle** [SamboyCoding/AudicaShredder#232]
hi i wante some dump dll for among us in pc here the command that i do : >Cpp2IL-2022.0.7-Windows.exe --game-path E:\Modded\AmongUs.exe --output-root E:\Modded\My project\DumpDll --force-unity-version 2020.3.45 --force-binary-path E:\Modded\AmongUs\GameAssembly.dll --force-metadata-path E:\Modded\AmongUs\Among Us_Data\il2cpp_data\Metadata\global-metadata.dat --just-give-me-dlls-asap-dammit --analyze-all 

**When i Click Enter** 

I throw a new error : 
`[Info] [Program] Running on Win32NT
[Warn] [Program] Using force options, I sure hope you know what you're doing!
[Warn] [Program] !!!!!!!!!!You have enabled IL-To-ASM. If this breaks, it breaks.!!!!!!!!!!
[Fail] [Program] !!!!!!!!!!Throwing safety out the window, as you requested! Forget "If this breaks, it breaks", this probably WILL break!!!!!!!!!!
[Fail] [Program]

Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'E:\Modded\AmongUs\Among'.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String , FileMode , FileAccess , FileShare , FileOptions )
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String , FileMode , FileAccess , FileShare , FileOptions , Int64 )
   at System.IO.File.ReadAllBytes(String )
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, Int32[] unityVersion)
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)`

And i wante do for an apk how please and thanks

**Comment by ds5678** [comment]
```
Cpp2IL-2022.0.7-Windows.exe --game-path E:\Modded\AmongUs.exe --output-root "E:\Modded\My project\DumpDll" --force-unity-version 2020.3.45 --force-binary-path E:\Modded\AmongUs\GameAssembly.dll --force-metadata-path "E:\Modded\AmongUs\Among Us_Data\il2cpp_data\Metadata\global-metadata.dat" --just-give-me-dlls-asap-dammit --analyze-all
```

**Comment by JeanTheFungle** [comment]
> ```
> Cpp2IL-2022.0.7-Windows.exe --game-path E:\Modded\AmongUs.exe --output-root "E:\Modded\My project\DumpDll" --force-unity-version 2020.3.45 --force-binary-path E:\Modded\AmongUs\GameAssembly.dll --force-metadata-path "E:\Modded\AmongUs\Among Us_Data\il2cpp_data\Metadata\global-metadata.dat" --just-give-me-dlls-asap-dammit --analyze-all
> ```

Thanks i solve the issue

**Comment by JeanTheFungle** [comment]
@ds5678 in AssetRipper the AuxilaryFiles when i put it to ILSPY it show me empty method

**Comment by JeanTheFungle** [comment]
answer me in discord
