### ISSUE TITLE
GUI build nopes out upon boot

### ISSUE THREAD

**Issue by modusc896d352** [SamboyCoding/AudicaShredder#277]
when starting-up **Cpp2IL.Gui.exe**, this is how it boots up
```
tarting Cpp2IL GUI. Initializing Cpp2IL Core...
[Info] [GUI] Starting Avalonia...
[Info] [GUI] Loading XAML...
Unhandled exception. System.MethodAccessException: Attempt to access the method failed.
   at Cpp2IL.Gui.App.!XamlIlPopulate(IServiceProvider, App)
   at Cpp2IL.Gui.App.!XamlIlPopulateTrampoline(App)
   at Cpp2IL.Gui.App.Initialize()
   at Avalonia.AppBuilder.Setup() in /_/src/Avalonia.Controls/AppBuilder.cs:line 248
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime) in /_/src/Avalonia.Controls/AppBuilder.cs:line 160
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], ShutdownMode ) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 211
   at Cpp2IL.Gui.Program.Main(String[])
```
"unhandled exception" message before the app self-destructs

**Comment by theodoreapeters** [comment]
same here

**Comment by SamboyCoding** [comment]
//TODO: Remove GUI
