### ISSUE TITLE
Cpp2IL.Plugin.StrippedCodeRegSupport.dll wont run

### ISSUE THREAD

**Issue by dimentox** [SamboyCoding/AudicaShredder#283]
[Info] [Plugins] Using Plugin: Orbis PKG
[Fail] [Plugins] Plugin Cpp2IL.Plugin.StrippedCodeRegSupport.StrippedCodeRegSupportPlugin threw an exception during OnLoad: System.MissingMethodException: Attempted to access a missing method.
   at Cpp2IL.Plugin.StrippedCodeRegSupport.StrippedCodeRegSupportPlugin.OnLoad()
   at Cpp2IL.Core.Cpp2IlPluginManager.InitAll() in /_/Cpp2IL.Core/Cpp2IlPluginManager.cs:line 70. It will not receive any further events.
Unhandled exception. System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Cpp2IL.Core.Cpp2IlPluginManager.InitAll() in /_/Cpp2IL.Core/Cpp2IlPluginManager.cs:line 66
   at Cpp2IL.Core.Cpp2IlApi.Init(String ) in /_/Cpp2IL.Core/Cpp2IlApi.cs:line 27
   at Cpp2IL.Program.GetRuntimeOptionsFromCommandLine(String[] commandLine) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 349
   at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 444

**Comment by SamboyCoding** [comment]
Are you definitely running the net7 build, not the netframework one? Netframework doesn't support plugins

**Comment by dimentox** [comment]
yes the latest build .

**Comment by dimentox** [comment]
SHA1 716d919cf578b53e6a70083d17e9faf882d79d30
Cpp2IL-2022.1.0-pre-release.14-Windows.exe

**Comment by SamboyCoding** [comment]
This has been fixed since last release.
