### ISSUE TITLE
Unity 2021 variant of v31 is not supported

### ISSUE THREAD

**Issue by moonheart** [SamboyCoding/AudicaShredder#317]
Hello, a game just updated its version and Cpp2IL is not working. 

I'm using latest CI version at https://github.com/SamboyCoding/Cpp2IL/tree/new-analysis

command line: `.\cpp2IL.exe  --skip-method-dumps  --experimental-enable-il-to-assembly-please  --throw-safety-out-the-window --skip-metadata-txts --analyze-all --suppress-attributes --game-path path\to\game`

```
===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.

[Info] [Program] Running on Win32NT
[Info] [Program] Determined game's unity version to be 2021.3.40
[Warn] [Program] !!!!!!!!!!You have enabled IL-To-ASM. If this breaks, it breaks.!!!!!!!!!!
[Fail] [Program] !!!!!!!!!!Throwing safety out the window, as you requested! Forget "If this breaks, it breaks", this probably WILL break!!!!!!!!!!
[Info] [Library] Initializing Metadata...
[Info] [Library]        Using actual IL2CPP Metadata version 31
[Info] [Library] Initialized Metadata in 658ms
[Info] [Library] Searching Binary for Required Data...
[Info] [Library] Got Binary codereg: 0x182C1A7A0, metareg: 0x1830F7D60 in 502ms.
[Info] [Library] Initializing Binary...
[Fail] [Program]

Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL! ---> System.OverflowException: Array dimensions exceeded supported range.
   at LibCpp2IL.ClassReadingBinaryReader.ReadClassArrayAtRawAddr[T](Int64 offset, Int64 count) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/ClassReadingBinaryReader.cs:line 238
   at LibCpp2IL.Il2CppBinary.Init(UInt64 pCodeRegistration, UInt64 pMetadataRegistration) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/Il2CppBinary.cs:line 67
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion) in /home/runner/work/Cpp2IL/Cpp2IL/LibCpp2IL/LibCpp2IlMain.cs:line 204
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in /home/runner/work/Cpp2IL/Cpp2IL/Cpp2IL.Core/Cpp2IlApi.cs:line 176
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in /home/runner/work/Cpp2IL/Cpp2IL/Cpp2IL.Core/Cpp2IlApi.cs:line 190
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in /home/runner/work/Cpp2IL/Cpp2IL/Cpp2IL/Program.cs:line 442
   at Cpp2IL.Program.Main(String[] args) in /home/runner/work/Cpp2IL/Cpp2IL/Cpp2IL/Program.cs:line 386

Waiting for you to press enter - feel free to copy the error...
```

**Comment by fedes1to** [comment]
having the same issue, cant export v31 even after the fix in the new-analysis branch

**Comment by mindphluxnet** [comment]
Same issue when throwing in "Hungry Shark Evolution 12.7.2":

[Info] [XAPK] Reading globalgamemanagers to determine unity version...
[Info] [XAPK] Determined game's unity version to be 2021.3.45
[Info] [Library] Initializing Metadata...
[Info] [Library]        Using actual IL2CPP Metadata version 31
[Info] [Library] Initialized Metadata in 820ms
[Info] [Library] Searching Binary for Required Data...
[Info] [Library] Got Binary codereg: 0x32F2320, metareg: 0x34288B0 in 1748ms.
[Info] [Library] Initializing Binary...
[Fail] [Program]

Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 )
   at LibCpp2IL.ClassReadingBinaryReader.ReadPrimitive(Type type, Boolean overrideArchCheck)
   at LibCpp2IL.ClassReadingBinaryReader.ReadAndConvertPrimitive(Boolean overrideArchCheck, Type type)
   at LibCpp2IL.ClassReadingBinaryReader.ReadClassArrayAtRawAddr[T](Int64 offset, Int64 count)
   at LibCpp2IL.Il2CppBinary.Init(UInt64 pCodeRegistration, UInt64 pMetadataRegistration)
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion)
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, Int32[] unityVersion)
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses)
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)
