### ISSUE TITLE
Cannot find codereg and metareg for 2022.3.21f1

### ISSUE THREAD

**Issue by Trung0246** [SamboyCoding/AudicaShredder#326]
Apk in question: https://apkpure.com/iriam/jp.co.duo7.vr.iriam/download

Relevant artifact (splitted with peazip, rename to `metadata-libil2cpp.zip.001)` and `metadata-libil2cpp.zip.002`
[metadata-libil2cpp.001.zip](https://github.com/user-attachments/files/16700824/metadata-libil2cpp.001.zip)
[metadata-libil2cpp.002.zip](https://github.com/user-attachments/files/16700828/metadata-libil2cpp.002.zip)

Log:

```log
===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.
Version 2022.1.0-pre-release.17+fa86c0910de2e852a320bbc6b897293ced9ff3f2

[Info] [Program] Running on Win32NT
[Info] [Plugins] Loading plugins from C:\Program Files (Sole)\jadx\output\jp.co.duo7.vr.iriam\Plugins...
[Info] [Plugins] Using Plugin: Cpp2IL Built-In
[Info] [XAPK] Attempting to extract required files from XAPK C:\Users\trung\Downloads\jp.co.duo7.vr.iriam.xapk
[Info] [XAPK] Identified APKs inside XAPK - config: config.arm64_v8a.apk, mainPackage: base.apk
[Info] [XAPK] Extracting XAPK/config.arm64_v8a.apk/lib/arm64-v8a/libil2cpp.so to C:\Users\trung\AppData\Local\Temp\tmp3FE0.tmp
[Info] [XAPK] Extracting XAPKbase.apk/assets/bin/Data/Managed/Metadata/global-metadata.dat to C:\Users\trung\AppData\Local\Temp\tmp3FE1.tmp
[Info] [XAPK] Reading globalgamemanagers to determine unity version...
[Info] [XAPK] Determined game's unity version to be 2022.3.21f1
[Info] [Library] Initializing Metadata...
[Info] [Library]        Using actual IL2CPP Metadata version 29.1
[Info] [Library] Initialized Metadata in 338ms
[Info] [Library] Using binary type ELF (from LibCpp2IL)
[Info] [Library] Searching Binary for Required Data...
[Fail] [Library]                        No codegen modules found for mscorlib! Aborting search.
[Info] [Library] Got Binary codereg: 0x0, metareg: 0x0 in 59ms.
[Info] [Library] Initializing Binary...
[Warn] [Library] At least one of the registration structs was not able to be found. Attempting to use fallback locator delegate to find them (this will fail unless you have a plugin that helps with this!)...
[Fail] [Program]

Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.Exception: Failed to find code registration or metadata registration!
   at LibCpp2IL.Il2CppBinary.Init(UInt64, UInt64) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\Il2CppBinary.cs:line 81
   at LibCpp2IL.LibCpp2IlBinaryRegistry.CreateAndInit(Byte[], Il2CppMetadata) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlBinaryRegistry.cs:line 72
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[], Byte[], UnityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 164
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String, String, UnityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 208
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String, String, UnityVersion, Boolean ) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 65
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String, String, UnityVersion, Boolean ) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 71
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 588
   at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 526

Waiting for you to press enter - feel free to copy the error...
```

**Comment by SamboyCoding** [comment]
This looks very unlikely to be specific to that unity version, and a lot more likely to be some form of protection on the game.

**Comment by Trung0246** [comment]
Interesting, what make you come to that conclusion? I tried to extract the asset with https://assetripper.github.io/AssetRipper/ and basic decompile through https://github.com/skylot/jadx and it seems to somewhat works except the actual unity file. Unless I'm missing something. https://github.com/Perfare/Il2CppDumper also accepted `global-metadata.dat` and the `libil2cpp.so`, but the only thing is cannot figure out codereg and metareg.

If it indeed some form of protection, I probably could close this issue since it maybe unrelevant.

**Comment by SamboyCoding** [comment]
You're saying perfare's dumper also couldn't find the two registration pointers? If so I definitely think there's some level of obfuscation.

Technically speaking, this error means that the string `mscorlib.dll` was not present anywhere in the libil2cpp.so file, which should not be possible. Hence why I say protected in some way - even if that protection is merely xor encryption on the strings.

**Comment by SamboyCoding** [comment]
In fact, someone in my discord just said this game uses https://www.hypertech.co.jp/. So definitely protected. So I'm going to close this issue

**Comment by Trung0246** [comment]
~~Hi, is there a discord link so I can join and discuss about this? Maybe I could manually comb through the assembly and see what's going on.~~

Edit: nvm it's right on the README. Thanks anyways.
