### ISSUE TITLE
--output-as diffable-cs Crash on latest Preview Milestone

### ISSUE THREAD

**Issue by mucookul** [SamboyCoding/AudicaShredder#330]
```
===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.
Version 2022.1.0-pre-release.17+fa86c0910de2e852a320bbc6b897293ced9ff3f2

[Info] [Program] Running on Win32NT
[Info] [Plugins] Loading plugins from C:\Users\Mukul\Downloads\Plugins...
[Info] [Plugins] Using Plugin: Cpp2IL Built-In
[Info] [Program] Determined game's unity version to be 2021.3.16a0
[Info] [Library] Initializing Metadata...
[Info] [Library]        Using actual IL2CPP Metadata version 29
[Info] [Library] Initialized Metadata in 271ms
[Info] [Library] Using binary type Portable Executable (from LibCpp2IL)
[Info] [Library] Searching Binary for Required Data...
[Info] [Library] Got Binary codereg: 0x184DF7D00, metareg: 0x18555FC60 in 110ms.
[Info] [Library] Initializing Binary...
[Info] [Library] Initialized Binary in 102ms
[Info] [Library] Mapping pointers to Il2CppMethodDefinitions...Processed 208559 OK (187ms)
[Info] [Program] Creating application model...
[Info] [Program] Application model created in 1794.3573ms
[Info] [Program] Pre-processing processing layers...
[Info] [Program]     Attribute Injector...
[Info] [Program]     Attribute Injector finished in 0.1552ms
[Info] [Program] Invoking processing layers...
[Info] [Program]     Attribute Injector...
[Info] [Program]     Attribute Injector finished in 405.3503ms
[Info] [Program] Outputting as Diffable C# to C:\Users\Mukul\Downloads\cpp2il_out...
[Info] [DiffableCsOutputFormat] Building C# files and directory structure...
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Cpp2IL.Core.Model.Contexts.ParameterAnalysisContext.ToString() in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Model\Contexts\ParameterAnalysisContext.cs:line 105
   at System.Text.StringBuilder.Append(Object )
   at Cpp2IL.Core.Utils.CsFileUtils.GetMethodParameterString(MethodAnalysisContext) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Utils\CsFileUtils.cs:line 30
   at Cpp2IL.Core.OutputFormats.DiffableCsOutputFormat.AppendMethod(StringBuilder, MethodAnalysisContext, Int32) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\OutputFormats\DiffableCsOutputFormat.cs:line 303
   at Cpp2IL.Core.OutputFormats.DiffableCsOutputFormat.AppendType(StringBuilder, TypeAnalysisContext, Int32 ) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\OutputFormats\DiffableCsOutputFormat.cs:line 154
   at Cpp2IL.Core.OutputFormats.DiffableCsOutputFormat.BuildOutput(ApplicationAnalysisContext, String) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\OutputFormats\DiffableCsOutputFormat.cs:line 74
   at Cpp2IL.Core.OutputFormats.DiffableCsOutputFormat.DoOutput(ApplicationAnalysisContext, String) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\OutputFormats\DiffableCsOutputFormat.cs:line 40
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 614
   at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 526
```

**Comment by ds5678** [comment]
Do you still experience the issue on the latest commit?

**Comment by mucookul** [comment]
Forgot about this issue but yep, it seems to be working on the latest commit:
```
# .\Cpp2IL.exe --game-path="C:\Program Files (x86)\Steam\steamapps\common\Trailmakers" --use-processor=attributeinjector --output-as=dummydll

===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.
Version 2022.1.0-development.1225+a067435.a067435d01d8e19cbbfe76b201c6c296eda63279

[Info] [Program] Running on Win32NT
[Info] [Plugins] Loading plugins from C:\Users\Mukul\Downloads\Plugins...
[Info] [Plugins] Using Plugin: Cpp2IL Built-In
[Info] [Program] Determined game's unity version to be 2021.3.16f1
[Info] [Library] Initializing Metadata...
[Info] [Library]        Using actual IL2CPP Metadata version 29
[Info] [Library] Initialized Metadata in 564ms
[Info] [Library] Using binary type Portable Executable (from LibCpp2IL)
[Info] [Library] Searching Binary for Required Data...
[Info] [Library] Got Binary codereg: 0x18528E870, metareg: 0x185A5ED30 in 480ms.
[Info] [Library] Initializing Binary...
[Info] [Library] Initialized Binary in 184ms
[Info] [Library] Mapping pointers to Il2CppMethodDefinitions...Processed 218453 OK (208ms)
[Info] [Program] Creating application model...
[Info] [Program] Application model created in 1875.7793ms
[Info] [Program] Pre-processing processing layers...
[Info] [Program]     Attribute Injector...
[Info] [Program]     Attribute Injector finished in 0.1588ms
[Info] [Program] Invoking processing layers...
[Info] [Program]     Attribute Injector...
[Info] [Program]     Attribute Injector finished in 576.7723ms
[Info] [Program] Outputting as DLL output format for backwards compatibility. to C:\Users\Mukul\Downloads\cpp2il_out...
[Info] [Program] Finished outputting in 6311.4603ms
[Info] [Program] Done. Total execution time: 10308.9289ms
```
