### ISSUE TITLE
DllSaveException Invalid Cast

### ISSUE THREAD

**Issue by MunWolf** [SamboyCoding/AudicaShredder#34]
I get the following exception when trying to analyse my dll.
Any help would be appreciated
```
[Fail] [Program] Cpp2IL.Core.Exceptions.DllSaveException: Fatal Exception writing DLL D:\Dev\WotwBepInExTest\Cpp2IL\cpp2il_out\System.dll
 ---> System.InvalidCastException: Specified cast is not valid.
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeElement(TypeReference type, CustomAttributeArgument argument)
   at Mono.Cecil.SignatureWriter.WriteCustomAttributeConstructorArguments(CustomAttribute attribute)
   at Mono.Cecil.MetadataBuilder.GetCustomAttributeSignature(CustomAttribute attribute)
   at Mono.Cecil.MetadataBuilder.AddCustomAttributes(ICustomAttributeProvider owner)
   at Mono.Cecil.MetadataBuilder.AddProperty(PropertyDefinition property)
   at Mono.Cecil.MetadataBuilder.AddProperties(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypes()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.MetadataBuilder.BuildMetadata()
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata)
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters)
   at Cpp2IL.Core.Cpp2IlApi.SaveAssemblies(String toWhere, List`1 assemblies)
   --- End of inner exception stack trace ---
   at Cpp2IL.Core.Cpp2IlApi.SaveAssemblies(String toWhere, List`1 assemblies)
   at Cpp2IL.Core.Cpp2IlApi.SaveAssemblies(String toWhere)
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)
```

**Comment by SamboyCoding** [comment]
Looks like I've missed something in the attribute analysis. Will take a look for you. Would be useful to know what the game is, however.

**Comment by MunWolf** [comment]
This is Ori and the Will of the Wisps

**Comment by SamboyCoding** [comment]
Sorry for the long delay on this, it's fixed now
