### ISSUE TITLE
TLD Linux Code Registration

### ISSUE THREAD

**Issue by ds5678** [SamboyCoding/AudicaShredder#380]
This is an issue to track the problem discussed in Discord about the Linux version of The Long Dark.

This is the stack trace without the plugin:
```
Failed to find code registration or metadata registration!
   at LibCpp2IL.Il2CppBinary.Init(UInt64 pCodeRegistration, UInt64 pMetadataRegistration) in E:\repos\Cpp2IL\LibCpp2IL\Il2CppBinary.cs:line 78
   at LibCpp2IL.LibCpp2IlBinaryRegistry.CreateAndInit(Byte[] buffer, Il2CppMetadata metadata) in E:\repos\Cpp2IL\LibCpp2IL\LibCpp2IlBinaryRegistry.cs:line 74
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, UnityVersion unityVersion) in E:\repos\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 164
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, UnityVersion unityVersion) in E:\repos\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 210
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in E:\repos\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 67
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in E:\repos\Cpp2IL\Cpp2IL\Program.cs:line 587
   at Cpp2IL.Program.Main(String[] args) in E:\repos\Cpp2IL\Cpp2IL\Program.cs:line 531
```

This is the stack trace with the plugin:
```
No entry in the Elf PHT contains virtual address 0x10102464C457F
   at LibCpp2IL.Elf.ElfFile.MapVirtualAddressToRaw(UInt64 addr, Boolean throwOnError) in E:\repos\Cpp2IL\LibCpp2IL\Elf\ElfFile.cs:line 689
   at LibCpp2IL.BinaryStructures.Il2CppCodeGenModule.get_Name() in E:\repos\Cpp2IL\LibCpp2IL\BinaryStructures\Il2CppCodeGenModule.cs:line 40
   at LibCpp2IL.Il2CppBinary.Init(UInt64 pCodeRegistration, UInt64 pMetadataRegistration) in E:\repos\Cpp2IL\LibCpp2IL\Il2CppBinary.cs:line 178
   at LibCpp2IL.LibCpp2IlBinaryRegistry.CreateAndInit(Byte[] buffer, Il2CppMetadata metadata) in E:\repos\Cpp2IL\LibCpp2IL\LibCpp2IlBinaryRegistry.cs:line 74
   at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, UnityVersion unityVersion) in E:\repos\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 164
   at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, UnityVersion unityVersion) in E:\repos\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 210
   at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in E:\repos\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 67
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in E:\repos\Cpp2IL\Cpp2IL\Program.cs:line 587
   at Cpp2IL.Program.Main(String[] args) in E:\repos\Cpp2IL\Cpp2IL\Program.cs:line 531
```

**Comment by ds5678** [comment]
I figured out why this is happening. The start of the modules list is off by 2. If I manually correct the address in `FindCodeGenModulesListFromMscorlib`, everything works fine.

```diff
- var startOfCodegenModulesList = endOfCodegenModulesList - ((moduleCount - 1) * pointerSize);
+ var startOfCodegenModulesList = endOfCodegenModulesList - ((moduleCount + 1) * pointerSize);
```

Now obviously, this hacky solution should not be used to solve the problem, but it's close.
