### ISSUE TITLE
AsmResolver fails during type lookups in BTD6

### ISSUE THREAD

**Issue by yeah-its-gloria** [SamboyCoding/AudicaShredder#384]
Cpp2IL currently fails an assert while trying to process Bloons TD 6's GameAssembly.

```
// ...
[Verb] [DllOutput] Adding fields, methods, properties, and events (in parallel)...Process terminated. Assertion failed.
   at Cpp2IL.Core.Utils.AsmResolver.AsmResolverUtils.InternalTryLookupTypeSignatureByName(String name, ReadOnlySpan`1 genericParameterNames) in (...)/Cpp2IL.Core/Utils/AsmResolver/AsmResolverUtils.cs:line 274
   at Cpp2IL.Core.Utils.AsmResolver.AsmResolverUtils.InternalTryLookupTypeSignatureByName(String name, ReadOnlySpan`1 genericParameterNames) in (...)/Cpp2IL.Core/Utils/AsmResolver/AsmResolverUtils.cs:line 290
   at Cpp2IL.Core.Utils.AsmResolver.AsmResolverUtils.TryLookupTypeSignatureByName(String name, ReadOnlySpan`1 genericParameterNames) in (...)/Cpp2IL.Core/Utils/AsmResolver/AsmResolverUtils.cs:line 244
   at Cpp2IL.Core.Utils.AsmResolver.AsmResolverAssemblyPopulator.InferExplicitInterfaceImplementations(TypeDefinition type, ReferenceImporter importer) in (...)/Cpp2IL.Core/Utils/AsmResolver/AsmResolverAssemblyPopulator.cs:line 576
   at Cpp2IL.Core.Utils.AsmResolver.AsmResolverAssemblyPopulator.InferExplicitInterfaceImplementations(AssemblyAnalysisContext asmContext) in (...)/Cpp2IL.Core/Utils/AsmResolver/AsmResolverAssemblyPopulator.cs:line 547
   at Cpp2IL.Core.Utils.MiscUtils.<>c__DisplayClass14_0`1.<ExecuteParallel>g__F2|0(T t) in (...)/Cpp2IL.Core/Utils/MiscUtils.cs:line 242
   at System.Linq.Parallel.SelectQueryOperator`2.SelectQueryOperatorResults.GetElement(Int32 index)
   at System.Linq.Parallel.QueryResults`1.get_Item(Int32 index)
   at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
   at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
   at System.Linq.Parallel.SpoolingTaskBase.Work()
   at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

The offending type in question is `System.Collections.Generic.IEnumerator<NinjaKiwi.Common.ResourceUtils.AssetLibrary<T>.Entry>`, where `.Entry` ends up inside the parsed type's Suffix, causing the assert to fail.

**Comment by ds5678** [comment]
Resolved by #414
