### ISSUE TITLE
Unhandled exception in Arm64 disassembler

### ISSUE THREAD

**Issue by tomrus88** [SamboyCoding/AudicaShredder#60]
I've tried to run Cpp2IL on [this apk](https://www.apkmirror.com/apk/blizzard-entertainment-inc/wow-legion-companion/wow-legion-companion-3-0-40928-release/wow-companion-3-0-40928-android-apk-download/) and got following exception
```
[Info] [Program] Running Scan for Known Functions...
[Info] [Program]        Running entire .text section through Arm64 disassembler, this might take up to several minutes for large games, and may fail on large games if you have <16GB ram...
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 )
   at Cpp2IL.Core.Arm64KeyFunctionAddresses..ctor()
   at Cpp2IL.Core.Cpp2IlApi.ScanForKeyFunctionAddresses()
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)
```

Then I've made slight change in the code so it can proceed past above problematic part and now it just spams following Exception in console and never finishes:
```
[Warn] [Analyze] Failed to perform analysis on method
While analysing instruction ldr q0, [x8, #0x240] at 0xD03314
Got exception: System.ArgumentException: Owner is null but reflection data T is a generic parameter, so needs an owner context. (Parameter 'owner')
   at Cpp2IL.Core.Utils.MiscUtils.TryResolveTypeReflectionData(Il2CppTypeReflectionData typeData, IGenericParameterProvider owner, IGenericParameterProvider[] extra) in e:\Cpp2IL\Cpp2IL.Core\Utils\MiscUtils.cs:line 582
   at Cpp2IL.Core.Utils.MiscUtils.TryResolveTypeReflectionData(Il2CppTypeReflectionData typeData) in e:\Dev\WoW\tools\Cpp2IL\Cpp2IL.Core\Utils\MiscUtils.cs:line 549
   at Cpp2IL.Core.Analysis.Actions.ARM64.Arm64MetadataUsageTypeToRegisterAction..ctor(MethodAnalysis`1 context, Arm64Instruction instruction) in e:\Cpp2IL\Cpp2IL.Core\Analysis\Actions\ARM64\Arm64MetadataUsageTypeToRegisterAction.cs:line 44
   at Cpp2IL.Core.Analysis.AsmAnalyzerArmV8A.CheckForTwoOpInstruction(Arm64Instruction instruction) in e:\Cpp2IL\Cpp2IL.Core\Analysis\AsmAnalyzerArmV8A.InstructionChecks.cs:line 231
   at Cpp2IL.Core.Analysis.AsmAnalyzerArmV8A.PerformInstructionChecks(Arm64Instruction instruction) in e:\Cpp2IL\Cpp2IL.Core\Analysis\AsmAnalyzerArmV8A.InstructionChecks.cs:line 28   at Cpp2IL.Core.Analysis.AsmAnalyzerBase`1.AnalyzeMethod() in e:\Cpp2IL\Cpp2IL.Core\Analysis\AsmAnalyzerBase.cs:line 374
```

**Comment by SamboyCoding** [comment]
Hi, issue received, I'll check it out tomorrow.

**Comment by SamboyCoding** [comment]
Should be all fixed for you
