### ISSUE TITLE
Support arm64 on unix

### ISSUE THREAD

**Issue by Martmists-GH** [SamboyCoding/AudicaShredder#66]
```
===Cpp2IL by Samboy063===
A Tool to Reverse Unity's "il2cpp" Build Process.

[Info] [Program] Running on Unix
[Warn] [Program] Using force options, I sure hope you know what you're doing!
[Info] [Program] Detected that Capstone's Managed assembly is missing. Attempting to copy the windows one...
[Warn] [Program] Couldn't find it at /home/mart/Downloads/Cpp2Il/runtimes/win-x64/lib/netstandard2.0/Gee.External.Capstone.dll. Your application will probably now throw an exception due to it being missing.
[Info] [Library] Initializing Metadata...
[Info] [Library] 	Using actual IL2CPP Metadata version 24.5
[Info] [Library] Initialized Metadata in 924ms
[Info] [Library] Searching Binary for Required Data...
[Info] [Library] Got Binary codereg: 0x4AC9F18, metareg: 0x4ACA5D8 in 2150ms.
[Info] [Library] Initializing Binary...
[Info] [Library] Initialized Binary in 344ms
[Info] [Library] Mapping Globals...OK (15ms)
[Info] [Library] Mapping pointers to Il2CppMethodDefinitions...Processed 70903 OK (37ms)
[Info] [Program] Building assemblies...This may take some time.
[Info] [Program] Finished Building Assemblies in 2435ms
[Info] [Program] Fixing up explicit overrides. Any warnings you see here aren't errors - they usually indicate improperly stripped or obfuscated types, but this is not a big deal. This should only take a second...
[Info] [Program] Fixup complete (102ms)
[Warn] [Program] Unable to hook native library resolving for Capstone. If you're not on windows and analysing an ARM or ARM64 binary, expect this to crash!
[Info] [Program] Running Scan for Known Functions...
Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'Gee.External.Capstone, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

File name: 'Gee.External.Capstone, Version=2.0.2.0, Culture=neutral, PublicKeyToken=null'
   at Cpp2IL.Core.Arm64KeyFunctionAddresses..ctor()
   at Cpp2IL.Core.Cpp2IlApi.ScanForKeyFunctionAddresses()
   at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs)
   at Cpp2IL.Program.Main(String[] args)
```

**Comment by SamboyCoding** [comment]
This is actually more of a Linux single-file-executable problem than anything specific to arm.
