### ISSUE TITLE
V29 Attribute Reader implementation isn't perfect

### ISSUE THREAD

**Issue by SamboyCoding** [SamboyCoding/AudicaShredder#77]
A log file was received in the MelonLoader discord which contained the following stacktrace:
```
[Info] [Program] Running processor Attribute Injector...
[ERROR]
[ERROR] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: CustomAttributePrimitiveParameter constructed with a non-primitive type: IL2CPP_TYPE_VALUETYPE
[ERROR]    at Cpp2IL.Core.Model.CustomAttributes.CustomAttributePrimitiveParameter.ReadFromV29Blob(BinaryReader reader, ApplicationAnalysisContext context) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Model\CustomAttributes\CustomAttributePrimitiveParameter.cs:line 92
[ERROR]    at Cpp2IL.Core.Model.CustomAttributes.CustomAttributeArrayParameter.ReadFromV29Blob(BinaryReader reader, ApplicationAnalysisContext context) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Model\CustomAttributes\CustomAttributeArrayParameter.cs:line 71
[ERROR]    at Cpp2IL.Core.Utils.V29AttributeUtils.ReadAttribute(Stream stream, MethodAnalysisContext constructor, ApplicationAnalysisContext context) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Utils\V29AttributeUtils.cs:line 42
[ERROR]    at Cpp2IL.Core.Model.Contexts.HasCustomAttributes.AnalyzeCustomAttributeDataV29() in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Model\Contexts\HasCustomAttributes.cs:line 219
[ERROR]    at Cpp2IL.Core.Model.Contexts.HasCustomAttributes.AnalyzeCustomAttributeData() in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Model\Contexts\HasCustomAttributes.cs:line 199
[ERROR]    at Cpp2IL.Core.CorePlugin.AttributeInjectorProcessingLayer.ProcessCustomAttributesForContext(HasCustomAttributes context, FieldAnalysisContext nameField, FieldAnalysisContext rvaField, FieldAnalysisContext offsetField, MethodAnalysisContext ctor) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AttributeInjectorProcessingLayer.cs:line 148
[ERROR]    at Cpp2IL.Core.CorePlugin.AttributeInjectorProcessingLayer.<>c__DisplayClass8_0.<InjectAttributeAttribute>b__1(HasCustomAttributes c) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AttributeInjectorProcessingLayer.cs:line 140
[ERROR]    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
[ERROR]    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
[ERROR]    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
[ERROR]    --- End of inner exception stack trace ---
[ERROR]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[ERROR]    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[ERROR]    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
[ERROR]    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
[ERROR]    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
[ERROR]    at Cpp2IL.Core.CorePlugin.AttributeInjectorProcessingLayer.InjectAttributeAttribute(ApplicationAnalysisContext appContext) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AttributeInjectorProcessingLayer.cs:line 125
[ERROR]    at Cpp2IL.Core.CorePlugin.AttributeInjectorProcessingLayer.Process(ApplicationAnalysisContext appContext, Action`2 progressCallback) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AttributeInjectorProcessingLayer.cs:line 19
[ERROR]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 331
[ERROR]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 268
```

Looking at the libil2cpp attribute reading code (Il2Cpp/vm-utils/BlobReader.cpp) on unity 2022.1.0b9, there is no handling for a value of type VALUETYPE, which implies that something has not been read correctly prior to this attribute. 

Two things should be done here. 
- Better handling of these sorts of errors, with information about the attribute currently being read, offset into its blob, etc.
    - This can be achieved by, for example, storing the number of bytes read by each attribute prior to this one, and logging this info out in the event of a failure.
- Fix the issue causing the exception.

Also - optionally - default the attributes to a failed state with only constructors, same as in versions < 29 when no analysis is run, allowing the injector to replace them with dummy attributes, etc. This should be possible, as constructor method indices are stored prior to any individual attribute data blobs.

The game in question was `Shredders`, available on steam (appid 1874171) and gamepass.

**Comment by SamboyCoding** [comment]
Fixed in https://github.com/SamboyCoding/Cpp2IL/commit/e6f1cc6a98cff4a27bbd80022421bf1d57fda5d3
