### ISSUE TITLE
Latest build fails to populate in VRChat

### ISSUE THREAD

**Issue by gompocp** [SamboyCoding/AudicaShredder#8]
I see you are still working actively on this but since its been broken for a bit now I thought I'd mention that release "Commit e0bb96b3b7b398b88305dbce365ccb4493086540" broke something and Cpp2Il fails when trying to populate assemblies for VRChat using that release and later ones
```cs
Populating 1753 types in assembly 1 of 93: mscorlib.dll...
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at Cpp2IL.AssemblyBuilder.ProcessTypeContents(Il2CppMetadata metadata, PE cppAssembly, Il2CppTypeDefinition cppTypeDefinition, TypeDefinition ilTypeDefinition, Il2CppImageDefinition imageDef)
   at Cpp2IL.AssemblyBuilder.ProcessAssemblyTypes(Il2CppMetadata metadata, PE theDll, Il2CppImageDefinition imageDef)
   at Cpp2IL.Program.Main(String[] args)
   ```
   
I've attached a log file here that may (or may not) help 
[log.txt](https://github.com/SamboyCoding/Cpp2IL/files/6012104/log.txt)

**Comment by SamboyCoding** [comment]
Ah yep, this is why I shouldn't write code while tired. One moment...

**Comment by SamboyCoding** [comment]
Fixed in above commit - will be available for download in ~2 minutes. Thanks for the report!
