### ISSUE TITLE
Failed to initialize LibCpp2IL: Failed to find pCodegenModules

### ISSUE THREAD

**Issue by ExHix** [SamboyCoding/AudicaShredder#80]
I am using MelonLoader to inject mod to an il2cpp game, and when it comes to initalize MelonLoader, it throws out the following error.
```[00:27:17.211] Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL! ---> System.Exception: Failed to find pCodegenModules
[00:27:17.211]    at LibCpp2IL.BinarySearcher.FindCodeRegistrationPost2019() in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\BinarySearcher.cs:line 174
[00:27:17.212]    at LibCpp2IL.Il2CppBinary.FindCodeAndMetadataReg(Int32 methodCount, Int32 typeDefinitionsCount) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\Il2CppBinary.cs:line 417
[00:27:17.213]    at LibCpp2IL.LibCpp2IlBinaryRegistry.CreateAndInit(Byte[] buffer, Il2CppMetadata metadata) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlBinaryRegistry.cs:line 62
[00:27:17.214]    at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 150
[00:27:17.215]    at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 159
[00:27:17.216]    --- End of internal exception stack monitoring ---
[00:27:17.216]    at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 171
[00:27:17.217]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) line C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 324
[00:27:17.218]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 268```

**Comment by SamboyCoding** [comment]
Run melonloader with --melonloader.debug, and then upload the full log file.

**Comment by ExHix** [comment]
````[00:53:44.681] [DEBUG] Initializing Mono...
[00:53:44.682] [DEBUG] Mono::BasePath = D:\Game\Umamusume\MelonLoader\Dependencies\MonoBleedingEdge.x64
[00:53:44.683] [DEBUG] Mono::ManagedPath = D:\Game\Umamusume\MelonLoader\Managed
[00:53:44.684] [DEBUG] Mono::ConfigPath = D:\Game\Umamusume\umamusume_Data\il2cpp_data\etc
[00:53:44.684] [DEBUG] Mono::IsOldMono = false

[00:53:44.685] ------------------------------
[00:53:44.685] MelonLoader v0.5.4 Open-Beta
[00:53:44.686] OS: Windows 10
[00:53:44.686] Hash Code: 99102531024810154100579910097100505048995753975597975597101485351514856
[00:53:44.686] ------------------------------
[00:53:44.686] Game Type: Il2Cpp
[00:53:44.687] Game Arch: x64
[00:53:44.687] ------------------------------

[00:53:44.688] Core::BasePath = D:\Game\Umamusume
[00:53:44.688] Game::BasePath = D:\Game\Umamusume
[00:53:44.688] Game::DataPath = D:\Game\Umamusume\umamusume_Data
[00:53:44.689] Game::ApplicationPath = D:\Game\Umamusume\umamusume.exe
[00:53:44.689] [DEBUG] Initializing Analytics Blocker...
[00:53:44.690] [DEBUG] Initializing wsock32...
[00:53:44.690] [DEBUG] Initializing wsock32 Exports...
[00:53:44.690] [DEBUG] gethostbyname
[00:53:44.691] [DEBUG] Initializing ws2_32...
[00:53:44.691] [DEBUG] Initializing ws2_32 Exports...
[00:53:44.691] [DEBUG] getaddrinfo
[00:53:44.692] [DEBUG] Initializing Il2Cpp...
[00:53:44.692] [DEBUG] Il2Cpp::GameAssemblyPath = D:\Game\Umamusume\GameAssembly.dll
[00:53:45.606] [DEBUG] Initializing Il2Cpp Exports...
[00:53:45.607] [DEBUG] il2cpp_init
[00:53:45.607] [DEBUG] il2cpp_runtime_invoke
[00:53:45.608] [DEBUG] il2cpp_method_get_name
[00:53:45.608] [DEBUG] Loading Mono Library...
[00:53:45.611] [DEBUG] Initializing Mono Exports...
[00:53:45.611] [DEBUG] mono_jit_init
[00:53:45.612] [DEBUG] mono_jit_parse_options
[00:53:45.612] [DEBUG] mono_thread_set_main
[00:53:45.613] [DEBUG] mono_thread_current
[00:53:45.614] [DEBUG] mono_add_internal_call
[00:53:45.614] [DEBUG] mono_lookup_internal_call
[00:53:45.615] [DEBUG] mono_runtime_invoke
[00:53:45.616] [DEBUG] mono_method_get_name
[00:53:45.616] [DEBUG] mono_domain_assembly_open
[00:53:45.617] [DEBUG] mono_assembly_get_image
[00:53:45.617] [DEBUG] mono_class_from_name
[00:53:45.618] [DEBUG] mono_class_get_name
[00:53:45.619] [DEBUG] mono_class_get_method_from_name
[00:53:45.619] [DEBUG] mono_string_to_utf8
[00:53:45.620] [DEBUG] mono_string_new
[00:53:45.620] [DEBUG] mono_object_get_class
[00:53:45.621] [DEBUG] mono_property_get_get_method
[00:53:45.621] [DEBUG] mono_image_get_name
[00:53:45.622] [DEBUG] mono_install_assembly_preload_hook
[00:53:45.623] [DEBUG] mono_install_assembly_search_hook
[00:53:45.623] [DEBUG] mono_install_assembly_load_hook
[00:53:45.624] [DEBUG] mono_assembly_get_object
[00:53:45.624] [DEBUG] mono_debug_init
[00:53:45.625] [DEBUG] mono_debug_domain_create
[00:53:45.626] [DEBUG] mono_domain_set_config
[00:53:45.626] [DEBUG] mono_free
[00:53:45.627] [DEBUG] mono_object_to_string
[00:53:45.627] [DEBUG] mono_set_assemblies_path
[00:53:45.632] [DEBUG] mono_assembly_setrootdir
[00:53:45.632] [DEBUG] mono_set_config_dir
[00:53:45.633] [DEBUG] mono_runtime_set_main_args
[00:53:45.633] [DEBUG] mono_raise_exception
[00:53:45.634] [DEBUG] mono_get_exception_bad_image_format
[00:53:45.635] [DEBUG] mono_image_open_full
[00:53:45.635] [DEBUG] mono_image_open_from_data_full
[00:53:45.636] [DEBUG] mono_image_close
[00:53:45.636] [DEBUG] mono_image_get_table_rows
[00:53:45.637] [DEBUG] mono_metadata_decode_table_row_col
[00:53:45.637] [DEBUG] mono_array_addr_with_size
[00:53:45.638] [DEBUG] mono_array_length
[00:53:45.639] [DEBUG] mono_metadata_string_heap
[00:53:45.639] [DEBUG] Attaching Hooks to wsock32...
[00:53:45.640] [DEBUG] gethostbyname
[00:53:45.640] [DEBUG] Attaching Hooks to ws2_32...
[00:53:45.641] [DEBUG] getaddrinfo
[00:53:45.641] [DEBUG] Attaching Hook to il2cpp_init...
[00:53:45.658] [DEBUG] Detaching Hook from il2cpp_init...
[00:53:45.659] [DEBUG] Creating Mono Domain...
[00:53:45.666] [DEBUG] Setting Mono Domain Config...
[00:53:45.666] [DEBUG] Initializing Internal Calls...
[00:53:45.667] [DEBUG] MelonLoader.MelonDebug::IsEnabled
[00:53:45.668] [DEBUG] MelonLoader.MelonLogger::Internal_PrintModName
[00:53:45.668] [DEBUG] MelonLoader.MelonLogger::Internal_Msg
[00:53:45.669] [DEBUG] MelonLoader.MelonLogger::Internal_Warning
[00:53:45.670] [DEBUG] MelonLoader.MelonLogger::Internal_Error
[00:53:45.670] [DEBUG] MelonLoader.MelonLogger::ThrowInternalFailure
[00:53:45.671] [DEBUG] MelonLoader.MelonLogger::WriteSpacer
[00:53:45.672] [DEBUG] MelonLoader.MelonLogger::Flush
[00:53:45.672] [DEBUG] MelonLoader.MelonUtils::IsGame32Bit
[00:53:45.673] [DEBUG] MelonLoader.MelonUtils::IsGameIl2Cpp
[00:53:45.674] [DEBUG] MelonLoader.MelonUtils::IsOldMono
[00:53:45.674] [DEBUG] MelonLoader.MelonUtils::IsUnderWineOrSteamProton
[00:53:45.675] [DEBUG] MelonLoader.MelonUtils::GetApplicationPath
[00:53:45.675] [DEBUG] MelonLoader.MelonUtils::GetGameDataDirectory
[00:53:45.678] [DEBUG] MelonLoader.MelonUtils::GetManagedDirectory
[00:53:45.679] [DEBUG] MelonLoader.MelonUtils::SetConsoleTitle
[00:53:45.679] [DEBUG] MelonLoader.MelonUtils::GetFileProductName
[00:53:45.680] [DEBUG] MelonLoader.MelonUtils::NativeHookAttach
[00:53:45.681] [DEBUG] MelonLoader.MelonUtils::NativeHookDetach
[00:53:45.681] [DEBUG] MelonLoader.MelonUtils::Internal_GetBaseDirectory
[00:53:45.682] [DEBUG] MelonLoader.MelonUtils::Internal_GetGameDirectory
[00:53:45.683] [DEBUG] MelonLoader.MelonUtils::Internal_GetHashCode
[00:53:45.683] [DEBUG] MelonLoader.Support.Preload::GetManagedDirectory
[00:53:45.684] [DEBUG] MelonLoader.MonoInternals.MonoLibrary::GetLibPtr
[00:53:45.684] [DEBUG] MelonLoader.MonoInternals.MonoLibrary::GetRootDomainPtr
[00:53:45.685] [DEBUG] MelonLoader.MonoInternals.MonoLibrary::CastManagedAssemblyPtr
[00:53:45.685] [DEBUG] MelonLoader.MonoInternals.ResolveInternals.AssemblyManager::InstallHooks
[00:53:45.686] [DEBUG] MelonLoader.InternalUtils.UnityInformationHandler::SetDefaultConsoleTitleWithGameName
[00:53:45.687] [DEBUG] MelonLoader.InternalUtils.Il2CppAssemblyGenerator::EnableCloseButton
[00:53:45.687] [DEBUG] MelonLoader.InternalUtils.Il2CppAssemblyGenerator::DisableCloseButton
[00:53:45.688] [DEBUG] MelonLoader.Il2CppAssemblyGenerator.Packages.Models.PackageBase::ThrowInternalFailure
[00:53:45.688] [DEBUG] MelonLoader.Il2CppAssemblyGenerator.Packages.Models.ExecutablePackage::SetProcessId
[00:53:45.689] [DEBUG] Initializing Base Assembly...

[00:53:46.179] ------------------------------
[00:53:46.180] Game Name: umamusume
[00:53:46.181] Game Developer: Cygames
[00:53:46.182] Unity Version: 2020.3.24f1
[00:53:46.183] Game Version: 1.17.0
[00:53:46.183] ------------------------------
[00:53:46.186] [DEBUG] [MonoLibrary] Setup Successful!
[00:53:46.191] [DEBUG] [MonoResolveManager] Setup Successful!
[00:53:46.418] Preferences Loaded!
[00:53:46.423] [DEBUG] bHaptics Native Library Loaded!
[00:53:46.428] [DEBUG] bHaptics Player Not Installed!
[00:53:46.429] [DEBUG] Disabling bHaptics API...
[00:53:46.433] [Il2CppUnityTls] Patching mono_unity_get_unitytls_interface...
[00:53:46.433] [Il2CppUnityTls] Patching il2cpp_unity_install_unitytls_interface...
[00:53:46.612] [Il2CppUnityTls] Calling Il2CppInstallUnityTlsInterface...
[00:53:46.613] [DEBUG] Loaded Compatibility Layer: Il2CppUnityTls.dll
[00:53:46.614] Loading Plugins...

[00:53:46.617] ------------------------------
[00:53:46.617] No Plugins Loaded!
[00:53:46.618] ------------------------------
[00:53:46.618] [DEBUG] Return Value = 0

[00:53:46.619] [DEBUG] Attaching Hook to il2cpp_runtime_invoke...
[00:53:46.620] [DEBUG] Creating Il2Cpp Domain...
[00:53:47.834] [DEBUG] Detaching Hook from il2cpp_runtime_invoke...
[00:53:47.837] [DEBUG] Pre-Starting Base Assembly...

[00:53:47.840] Loading Il2CppAssemblyGenerator...
[00:53:47.869] Contacting RemoteAPI...
[00:53:47.870] [DEBUG] ContactURL = https://api.melonloader.com/api/v1/game/umamusume
[00:53:47.921] [DEBUG] Unique Host Name or IP Found: api.melonloader.com
[00:53:49.213] [DEBUG] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/umamusume)
[00:53:49.213] RemoteAPI.DumperVersion = null
[00:53:49.214] RemoteAPI.UnhollowerVersion = null
[00:53:49.215] RemoteAPI.ObfuscationRegex = null
[00:53:49.215] RemoteAPI.MappingURL = null
[00:53:49.215] RemoteAPI.MappingFileSHA512 = null
[00:53:49.217] Using Dumper Version: 2022.1.0-pre-release.3
[00:53:49.217] Using Il2CppAssemblyUnhollower Version = 0.4.18.0
[00:53:49.218] Using Unity Dependencies Version = 2020.3.24
[00:53:49.218] Using Deobfuscation Regex = null
[00:53:49.219] Cpp2IL is up to date.
[00:53:49.219] Il2CppAssemblyUnhollower is up to date.
[00:53:49.220] UnityDependencies is up to date.
[00:53:49.220] Checking GameAssembly...
[00:53:49.221] [DEBUG] Last GameAssembly Hash:
[00:53:49.557] [DEBUG] Current GameAssembly Hash: 1ae5505d3fc9d87d160151615204348a274f04a50a7f4c41b8f1e011c21343cc5a7ef20064c5df84b9c90aba50280881c394d9c91d51e2e712cb3db46cbc18f3
[00:53:49.558] Assembly Generation Needed!
[00:53:49.562] Executing Cpp2IL...
[00:53:49.564] "D:\Game\Umamusume\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Cpp2IL.exe" --verbose --game-path "D:\Game\Umamusume" --exe-name "umamusume" --use-processor attributeinjector --output-as dummydll
[00:53:49.620] ===Cpp2IL by Samboy063===
[00:53:49.621] A Tool to Reverse Unity's "il2cpp" Build Process.
[00:53:49.621] Version 2022.1.0-pre-release.3
[00:53:49.622]
[00:53:49.622] [Warn] [Program] NO_COLOR set, disabling ANSI color codes as you requested.
[00:53:49.623] [Info] [Program] Running on Win32NT
[00:53:49.701] [Verb] [Plugins] Collecting and instantiating plugins...
[00:53:49.702] [Verb] [Plugins]         Loading plugin Cpp2IL.Core.CorePlugin.Cpp2IlCorePlugin from assembly: Cpp2IL.Core.dll
[00:53:49.703] [Verb] [Plugins] Invoking OnLoad on 1 plugins.
[00:53:49.703] [Verb] [Core Plugin] Initializing...
[00:53:49.704] [Verb] [Core Plugin]     Registering built-in instruction set handlers...
[00:53:49.705] [Verb] [Core Plugin]     Registering built-in binary parsers...
[00:53:49.705] [Verb] [Core Plugin]     Registering built-in output formats...
[00:53:49.706] [Verb] [Core Plugin]     Registering built-in processing layers
[00:53:49.707] [Verb] [Core Plugin] Core plugin loaded in 30012 ticks (3.0012ms)
[00:53:49.707] [Info] [Plugins] Using Plugin: Cpp2IL Built-In
[00:53:49.708] [Verb] [Plugins] OnLoad complete
[00:53:49.712] [Verb] [Program] Found probable windows game at path: D:\Game\Umamusume. Attempting to get unity version...
[00:53:49.715] [Verb] [Program] First-attempt unity version detection gave: System.Int32[]
[00:53:49.716] [Info] [Program] Determined game's unity version to be 2020.3.24
[00:53:49.716] [Verb] [Program] Selected output format: Stub ("Dummy") DLL Files
[00:53:49.717] [Verb] [Program] Selected processing layers: Attribute Injector
[00:53:49.765] [Info] [Library] Initializing Metadata...
[00:53:49.766] [Verb] [Library]         IL2CPP Metadata Declares its version as 27
[00:53:49.767] [Info] [Library]         Using actual IL2CPP Metadata version 27.1
[00:53:49.784] [Verb] [Library]         Reading image definitions...OK (3.001 ms)
[00:53:49.785] [Verb] [Library]         Reading assembly definitions...OK (0 ms)
[00:53:49.939] [Verb] [Library]         Reading type definitions...22766 OK (154.0348 ms)
[00:53:49.951] [Verb] [Library]         Reading interface offsets...OK (12.0023 ms)
[00:53:49.975] [Verb] [Library]         Reading vtable indices...OK (25.0059 ms)
[00:53:50.439] [Verb] [Library]         Reading method definitions...OK (463.1044 ms)
[00:53:50.558] [Verb] [Library]         Reading method parameter definitions...OK (120.0272 ms)
[00:53:50.676] [Verb] [Library]         Reading field definitions...OK (117.0265 ms)
[00:53:50.705] [Verb] [Library]         Reading default field values...OK (30.0072 ms)
[00:53:50.712] [Verb] [Library]         Reading default parameter values...OK (6.0003 ms)
[00:53:50.744] [Verb] [Library]         Reading property definitions...OK (32.0082 ms)
[00:53:50.745] [Verb] [Library]         Reading interface definitions...OK (1.9995 ms)
[00:53:50.746] [Verb] [Library]         Reading nested type definitions...OK (1.0008 ms)
[00:53:50.747] [Verb] [Library]         Reading event definitions...OK (0 ms)
[00:53:50.748] [Verb] [Library]         Reading generic container definitions...OK (2.0013 ms)
[00:53:50.751] [Verb] [Library]         Reading generic parameter definitions...OK (2.0001 ms)
[00:53:50.751] [Verb] [Library]         Reading generic parameter constraint indices...OK (0 ms)
[00:53:50.752] [Verb] [Library]         Reading referenced assemblies...OK (0 ms)
[00:53:50.765] [Verb] [Library]         Reading string definitions...OK (15.0036 ms)
[00:53:50.766] [Verb] [Library]         Reading field references...OK (0 ms)
[00:53:50.848] [Verb] [Library]         Reading attribute types...OK (82.0177 ms)
[00:53:50.851] [Verb] [Library]         Building Lookup Table for field defaults...OK (3.0005 ms)
[00:53:50.851] [Info] [Library] Initialized Metadata in 1086ms
[00:53:50.852] [Info] [Library] Using binary type Portable Executable (from LibCpp2IL)
[00:53:50.853] [Info] [Library] Searching Binary for Required Data...
[00:53:50.855] [Verb] [Library]         Reading PE File Header...OK (0 ms)
[00:53:50.856] [Verb] [Library]                 Image Base at 0x180000000
[00:53:50.857] [Verb] [Library]                 DLL is 64-bit
[00:53:50.857] [Verb] [Library]         Attempting to locate code and metadata registration functions...
[00:53:50.858] [Verb] [Library]                 -Searching for MetadataReg...
[00:53:50.860] [Verb] [Library]                         Looking for the number of type definitions, 0x58EE
[00:53:50.864] [Verb] [Library]                         Looking for bytes: ee 58 00 00 00 00 00 00
[00:53:50.889] [Verb] [Library]                         Found 0 instances of the number of type definitions: []
[00:53:50.890] [Verb] [Library]                         Found 0 potential metadata registrations: []
[00:53:50.891] [Verb] [Library]                 -Searching for CodeReg...
[00:53:50.891] [Verb] [Library]                         Using mscorlib full-disassembly approach to get codereg, this may take a while...
[00:53:50.894] [Verb] [Library]                         Looking for bytes: 6d 73 63 6f 72 6c 69 62 2e 64 6c 6c 00
[00:53:50.917] [Verb] [Library]                         Found 0 occurrences of mscorlib.dll: []
[00:53:50.919] [Verb] [Library]                         Found 0 potential codegen modules for mscorlib: []
[00:53:50.920] [Verb] [Library]                         Found 0 address for potential codegen modules in potential codegen module lists: []
[00:53:50.934] [Fail] [Program]
[00:53:50.935]
[00:53:50.936] Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL! ---> System.Exception: Failed to find pCodegenModules
[00:53:50.937]    at LibCpp2IL.BinarySearcher.FindCodeRegistrationPost2019() in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\BinarySearcher.cs:line 174
[00:53:50.939]    at LibCpp2IL.Il2CppBinary.FindCodeAndMetadataReg(Int32 methodCount, Int32 typeDefinitionsCount) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\Il2CppBinary.cs:line 417
[00:53:50.940]    at LibCpp2IL.LibCpp2IlBinaryRegistry.CreateAndInit(Byte[] buffer, Il2CppMetadata metadata) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlBinaryRegistry.cs:line 62
[00:53:50.940]    at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, Int32[] unityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 150
[00:53:50.941]    at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 159
[00:53:50.942]    --- End of internal exception stack monitoring ---
[00:53:50.943]    at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, Int32[] unityVersion, Boolean allowUserToInputAddresses) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 171
[00:53:50.944]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 324
[00:53:50.944]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 268
[00:53:50.945]
[00:53:50.946] Waiting for you to press enter - feel free to copy the error...``

**Comment by SamboyCoding** [comment]
It would appear that your game's assembly is packed or protected in some way, so cpp2il cannot read it.

**Comment by ExHix** [comment]
yeah the gameassembly.dll has an protected layer, so i wonder whether cpp2il read the dll directly or from the memory, for i can dump the unproteced dll by using [KsDumper](https://github.com/EquiFox/KsDumper) and use il2cppDumper to dump it

**Comment by SamboyCoding** [comment]
Cpp2il can't and it would take quite a lot of hackery to get melonloader to accept dlls generated as such, and that's assuming that they'd even function correctly.

**Comment by ExHix** [comment]
ok fine, thanks for your support
