### ISSUE TITLE
Value cannot be null exception 

### ISSUE THREAD

**Issue by MishaTy** [SamboyCoding/AudicaShredder#9]
Hi, there is a null reference exception in the part where it generates the IL code. 

Here is the full error: 
System.ArgumentNullException: Value cannot be null. (Parameter 'parameter')
   at Mono.Cecil.Cil.Instruction.Create(OpCode opcode, ParameterDefinition parameter)
   at Cpp2IL.Analysis.ResultModels.LocalDefinition.GetILToLoad(MethodAnalysis context, ILProcessor processor)
   at Cpp2IL.Analysis.Actions.Important.FieldToLocalAction.ToILInstructions(MethodAnalysis context, ILProcessor processor)
   at Cpp2IL.Analysis.AsmDumper.AnalyzeMethod(StringBuilder typeDump, List`1& allUsedMnemonics)

The game is Among Us.

**Comment by SamboyCoding** [comment]
Thank you, will investigate.

**Comment by SamboyCoding** [comment]
Ok I've been through Among Us and cleaned out most of the unhandled exceptions (I've been developing against a very simple, 64-bit assembly for the last week or two, so some of the new features I implemented broke when they encountered among us, which is 32-bit).

Changes are in 8fd256a if you're curious.

There's still one type (RewiredStandaloneInputModule) which is causing issues, on account of the fact it uses a generic constructor which can't be found, but everything else at least isn't spitting errors out. YMMV on how useful you actually find the generated IL, though - it's still in an early stage.
